config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"  # ルートパスを/postsに設定する場合はコメントアウトを解除してください

  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    # set_post メソッドで @post を設定しているので、ここでは特にすることはありません
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestPj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>投稿を編集</h1>

<%= form_with model: @post, html:{ class: "form-container" } do |form| %>
<div class= "form-input">
    <%= form.label :title %><%= form.text_field :title %>
</div>
<div class= "form-input"> 
    <%= form.label :content %><%= form.text_area :content %>
</div>
<div class= "button-container"><%= form.submit "編集" , class:"link-button" %>
</div>
<% end %> 

app/views/posts/index.html.erb
	<h1>Hello Ruby</h1>

	<div class="button-container" >
	<%= link_to "新しい投稿", new_post_path , class:"link-button"%>
	</div>

<ul>
		<% @posts.each do |post| %>
	<li>
		<h2><%= post.title%></h2>
		<p><%= post.content %></p>
		<span>
			<small><%= post.created_at %></small>
		</span> 
		<div class="edit-delete-wrapper">
			<%= link_to "編集", edit_post_path(post), class: "link-button" %>
			<%= button_to "削除" , post_path(post), method: :delete, class:"link-delete-button" %>
		</div>
	</li>
	<% end %>
</ul>

app/views/posts/new.html.erb
<h1>新しい投稿</h1>

<%= form_with model: @post, html:{ class: "form-container" } do |form| %>
   <div class= "form-input"> <%= form.label :title %><%= form.text_field :title %> </div>
   <div class= "form-input"> <%= form.label :content %><%= form.text_area :content %> </div>
   <div class= "button-container"><%= form.submit "投稿" , class:"link-button" %></div>
<% end %> 